- title: Public Tech R&D
  description: Onderzoeken van nieuwe technologieën voor toepassing in public tech.
- title: Public Tech Innovatie
  description: Ontwikkeling van nieuwe product- en dienstconcepten.
- title: Public Tech Educatie
  description: Workshops, trainingen en masterclasses over ontwikkelingen in public tech.